// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Alex Romantsov"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/handling_list/by_client": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Получение словаря услуг по типу клиента (физ или юр лицо)",
                "parameters": [
                    {
                        "enum": [
                            1,
                            2
                        ],
                        "type": "integer",
                        "x-enum-varnames": [
                            "IndividualClientType",
                            "EnterpriseClientType"
                        ],
                        "name": "client_type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.GetHandlingListByClientResponse"
                        }
                    }
                }
            }
        },
        "/office/location": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Получение ближайших отделений с загруженностью",
                "parameters": [
                    {
                        "description": "office location list request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.GetOfficeLocationListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.GetOfficeLocationListResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.GetHandlingListByClientResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.GetHandlingListByClientResponseData"
                    }
                }
            }
        },
        "handlers.GetHandlingListByClientResponseData": {
            "type": "object",
            "properties": {
                "client_type": {
                    "$ref": "#/definitions/model.ClientType"
                },
                "handling_duration": {
                    "description": "в секундах",
                    "type": "number"
                },
                "handling_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "handlers.GetOfficeLocationListRequest": {
            "type": "object",
            "required": [
                "latitude",
                "longitude"
            ],
            "properties": {
                "filter": {
                    "$ref": "#/definitions/handlers.GetOfficeLocationListRequestFilter"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                }
            }
        },
        "handlers.GetOfficeLocationListRequestFilter": {
            "type": "object",
            "required": [
                "client_type",
                "handling_type"
            ],
            "properties": {
                "client_type": {
                    "$ref": "#/definitions/model.ClientType"
                },
                "handling_type": {
                    "type": "integer"
                }
            }
        },
        "handlers.GetOfficeLocationListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.GetOfficeLocationListResponseData"
                    }
                }
            }
        },
        "handlers.GetOfficeLocationListResponseData": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "client_types": {
                    "description": "Обслуживание Физ. лица или Юр. лица",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ClientType"
                    }
                },
                "count_people": {
                    "description": "Кол-во людей в очереди",
                    "type": "integer"
                },
                "distance": {
                    "type": "number"
                },
                "handling_duration": {
                    "type": "number"
                },
                "handling_types": {
                    "description": "Обслуживание Физ. лица или Юр. лица",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "has_ramp": {
                    "type": "boolean"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "metro_station": {
                    "type": "string"
                },
                "officeName": {
                    "type": "string"
                },
                "office_id": {
                    "type": "integer"
                },
                "rate": {
                    "type": "number"
                },
                "timetable_enterprise": {
                    "description": "Расписание работы для Юр. лиц",
                    "allOf": [
                        {
                            "$ref": "#/definitions/handlers.GetOfficeLocationListResponseDataOfficeTimeTable"
                        }
                    ]
                },
                "timetable_individual": {
                    "description": "Расписание работы для Физ. лиц",
                    "allOf": [
                        {
                            "$ref": "#/definitions/handlers.GetOfficeLocationListResponseDataOfficeTimeTable"
                        }
                    ]
                },
                "travel_duration_car": {
                    "description": "Время на маршрут на машине",
                    "type": "number"
                },
                "travel_duration_human": {
                    "description": "Время на маршрут пешком",
                    "type": "number"
                },
                "wait_time": {
                    "description": "В секундах",
                    "type": "number"
                },
                "workload_koef": {
                    "type": "number"
                }
            }
        },
        "handlers.GetOfficeLocationListResponseDataDayTimeTable": {
            "type": "object",
            "properties": {
                "day": {
                    "type": "string"
                },
                "start": {
                    "type": "string"
                },
                "stop": {
                    "type": "string"
                }
            }
        },
        "handlers.GetOfficeLocationListResponseDataOfficeTimeTable": {
            "type": "object",
            "properties": {
                "days": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.GetOfficeLocationListResponseDataDayTimeTable"
                    }
                }
            }
        },
        "model.ClientType": {
            "type": "integer",
            "enum": [
                1,
                2
            ],
            "x-enum-varnames": [
                "IndividualClientType",
                "EnterpriseClientType"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "0.0.0.0:8070",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "vtbMapAPI",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
